// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFYc2PaExvb-Acgb1MRQd9p80rXeOYFWE',
    appId: '1:296404808067:web:4286dd458f5a4b0f8dc6b6',
    messagingSenderId: '296404808067',
    projectId: 'fee-verification-cp',
    authDomain: 'fee-verification-cp.firebaseapp.com',
    storageBucket: 'fee-verification-cp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4ObJdIDqLwCcLzFGy58Mp-yCtxHch_io',
    appId: '1:296404808067:android:8ead71c8f5b6ac828dc6b6',
    messagingSenderId: '296404808067',
    projectId: 'fee-verification-cp',
    storageBucket: 'fee-verification-cp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_XhokAT9X_KQzMZ1YKel5EmyOd9D23Aw',
    appId: '1:296404808067:ios:5cec7dd6665cf8df8dc6b6',
    messagingSenderId: '296404808067',
    projectId: 'fee-verification-cp',
    storageBucket: 'fee-verification-cp.appspot.com',
    iosBundleId: 'com.example.feeVerificationStudent',
  );
}
